name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 0.1
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: unit testing
        run: |
          . ./env-setup.sh
          python -m pytest Tests/*

      - name: Docker login
        run: docker login -u $docker_username -p $docker_password

      - name: Build image
        run: docker build -t am0072008/bdm-flask:$version -f ./docker/Dockerfile .

      - name: Pushing spring app image
        run: docker push am0072008/bdm-flask:$version